// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemBlMlzAQebi_npcTRA9nSOPhpuo_R3g',
    appId: '1:1073180507599:web:d0130eea71e93c92c226ba',
    messagingSenderId: '1073180507599',
    projectId: 'flutterfirebase-drdetails-app',
    authDomain: 'flutterfirebase-drdetails-app.firebaseapp.com',
    storageBucket: 'flutterfirebase-drdetails-app.appspot.com',
    measurementId: 'G-PEHPJ723WN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_PlTnpcXigwONfHxmcij2Ypc_3mxVrAU',
    appId: '1:1073180507599:android:9c714f79de6b0566c226ba',
    messagingSenderId: '1073180507599',
    projectId: 'flutterfirebase-drdetails-app',
    storageBucket: 'flutterfirebase-drdetails-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOW2z77p1mP0GbvFHGgkwSCx5dUm7ka7Q',
    appId: '1:1073180507599:ios:e4b29c504aa67137c226ba',
    messagingSenderId: '1073180507599',
    projectId: 'flutterfirebase-drdetails-app',
    storageBucket: 'flutterfirebase-drdetails-app.appspot.com',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOW2z77p1mP0GbvFHGgkwSCx5dUm7ka7Q',
    appId: '1:1073180507599:ios:998a39dadad5539cc226ba',
    messagingSenderId: '1073180507599',
    projectId: 'flutterfirebase-drdetails-app',
    storageBucket: 'flutterfirebase-drdetails-app.appspot.com',
    iosBundleId: 'com.example.flutterApplication4.RunnerTests',
  );
}
